config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'shows#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :shows, only: [:index, :show] do
    post :mark_favorite
    post :remove_favorite
    get :favorites, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
# frozen_string_literal: true

class Channel < ApplicationRecord
  has_many :shows

  validates :name, presence: true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/show.rb
# frozen_string_literal: true

class Show < ApplicationRecord
  belongs_to :channel
  has_many :favorites
  has_many :users, through: :favorites

  validates :name, :start_time, presence: true

  after_create :notify_users

  def notify_users
  	ShowScheduleWorker.perform_at(self.start_time - 30.minutes, self.id)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites
  has_many :shows, through: :favorites

  validates :email, format: { with: /(\A([a-z]*\s*)*\<*([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\>*\Z)/i }

  def favorite?(show_id)
    self.favorites.where(show_id: show_id).exists?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/shows_controller.rb
# frozen_string_literal: true

class ShowsController < ApplicationController
  def index
    @shows = Show.includes(:channel).order(created_at: :desc)
    @shows = @shows.joins(:channel).where('shows.name LIKE ? OR channels.name LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
  end

  def favorites
    @favorite_shows = current_user.shows.includes(:channel)
  end

  def mark_favorite
    show = Show.find(params[:show_id])
    if current_user.favorites.where(show_id: show.id).first_or_create!
      flash.notice = 'Yeay! Show set as favorite!'
    else
      flash.alert = 'Could not mark show as favorite!'
    end
    if params[:back_page] == 'favorites'
      redirect_to favorites_shows_path
    else
      redirect_to shows_path(search: params[:search])
    end
  end

  def remove_favorite
    show = Show.find(params[:show_id])
    if current_user.favorites.where(show_id: show.id).first&.destroy
      flash.notice = 'Show removed from favorites!'
    else
      flash.alert = 'Could not remove show from favorite!'
    end
    if params[:back_page] == 'favorites'
      redirect_to favorites_shows_path
    else
      redirect_to shows_path(search: params[:search])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_sidebar.html.erb
<!-- row -->
<div class="row">
    <div class="col-sm-12">
        <!-- Website Menu -->
        <ul class="menu boxed clearfix bg-image-home">
            <li><%= link_to root_path do %><i class="menu-icon menu-icon-1"></i>TV HOME<% end %></li>
            <li><%= link_to favorites_shows_path do %><i class="menu-icon menu-icon-6"></i>FAVORITES<% end %></li>
            <% if user_signed_in? %>
                <li><%= link_to edit_user_registration_path do %><i class="menu-icon menu-icon-7"></i><%= current_user.email.upcase %><% end %></li>
                <li><%= link_to destroy_user_session_path, method: :delete do %><i class="menu-icon menu-icon-7"></i>LOGOUT<% end %></li>
              <% else %>
                <li><%= link_to new_user_registration_path do %><i class="menu-icon menu-icon-7"></i>SIGN UP<% end %></li>
                <li><%= link_to destroy_user_session_path, method: :delete do %><i class="menu-icon menu-icon-7"></i>LOGIN<% end %></li>
              <% end %>
        </ul>
        <!--/ Website Menu -->
    </div>
</div>
<!--/ row -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EntertainmentOnline</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="body-wrap">
      <div class="content">
        <!--container-->
        <div class="container">
          <%= render partial: 'layouts/sidebar' %>
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shows/_show_card.html.erb
<div class="post-item boxed quotes">
    <div class="post-content bg-image-quotes">
        <h2 class="post-title"><a href="#"><%= show.name %></a></h2>
        <ul class="post-links-alt">
            <li class="post-date"><a href="#">Channel: <%= show.channel.name %></a></li> |
         	<!-- Need clarification on timezone -->
            <li class="post-author"><a href="#">Time: <%= show.start_time&.strftime("%d %b %Y %I:%M %p") %> </a></li> |
            <% if current_user.favorite?(show.id) %>
                <li class="post-date"><%= link_to 'Remove from Favorites', show_remove_favorite_path(show, search: params[:search], back_page: params[:action]), method: :post %></li>
            <% else %>
                <li class="post-date"><%= link_to 'Add to Favorites!', show_mark_favorite_path(show, search: params[:search], back_page: params[:action]), method: :post %></li>
            <% end %>
        </ul>
    </div>
</div>

app/views/shows/favorites.html.erb
<div class="row">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-12">
                <h1>Your Favorites!</h1>
            </div>
        </div>
        <% @favorite_shows.each do |show| %>
            <div class="row">
                <div class="col-sm-12">
                    <%= render partial: 'shows/show_card', locals: { show: show } %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/shows/index.html.erb
<div class="row">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-12">
                <div class="widget-search boxed">
                    <%= form_tag('shows', method: "get") do %>
                      <div class="field_text"><label for="search" class="label_title">Search Your Channel or Show</label>
                      <%= text_field_tag :search %></div>
                      <span class="btn btn-green btn-caps"><%= submit_tag("Search") %></span>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <h1><%= params[:search].present? ? 'Search Results' : 'Latest Shows' %></h1>
            </div>
        </div>
        <% @shows.each do |show| %>
            <div class="row">
                <div class="col-sm-12">
                    <%= render partial: 'shows/show_card', locals: { show: show } %>
                </div>
            </div>
        <% end %>
    </div>
</div>